ConnectionStrings: 
    PricingConnection: User ID=postgres;Password=Password1234;Database="Microservices.Demo.Pricing";Host=microservices.demo.pricing.db;Port=5432
ElasticApm:
    SecretToken: 
    ServerUrls: http://microservices.demo.apm-server:8200
    ServiceName: Microservices.Demo.Pricing.API
    Environment: production
